apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep4
spec:
  replicas: 5
  selector:
    matchLabels:
      mykey: myvalue
  template:                                   # pod definition starts from here
    metadata:
      name: pod4
      labels:
        mykey: myvalue
    spec:
      containers:
      - name: container4
        image: sadedil/simpleinfoserver:1.0.0 # something is hiding here (1.0.0)
        ports:
        - containerPort: 80
---
apiVersion: v1                                # service definition starts from here
kind: Service
metadata:
  name: service-for-myvalue 
spec:
  type: NodePort                              # Try to LoadBalancer if you deploy this yaml to any cloud service
  selector:
    mykey: myvalue
  ports:
  - name: http
    protocol: TCP
    port: 80                                  # The application's port, running in the container
    targetPort: 80                            # By default the targetPort will be set to the same value as the port field