apiVersion: v1
kind: ReplicationController
metadata:
  name: rc3
spec:
  replicas: 3
  selector:
    mykey: myvalue
  template: # pod definition starts from here
    metadata:
      name: pod3
      labels:
        mykey: myvalue
    spec:
      containers:
      - name: container3
        image: sadedil/simpleinfoserver:latest
        ports:
        - containerPort: 80
---
# service definition starts from here
apiVersion: v1
kind: Service
metadata:
  name: service-for-myvalue 
spec:
  type: NodePort # Try to LoadBalancer if you deploy this yaml to any cloud service
  selector:
    mykey: myvalue
  ports:
  - name: http
    protocol: TCP
    port: 80 # The application's port, running in the container
    targetPort: 80 # By default the targetPort will be set to the same value as the port field